### ISSUE TITLE
Prune_transcripts.py

### ISSUE THREAD

**Issue by sofinabegum** [alexfields/ORF-RATER#6] opened 2017-06-28 15:55 UTC
```
`Traceback (most recent call last):
  File "prune_transcripts.py", line 229, in <module>
    mm_df = workers.map(_find_mm_in_range, range(npart))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: No objects to concatenate
`
```
Hi Alex,

I get the above error when running prune_transcripts.py. I've indexed my bam files, so that's not an issue. 
In case anyone else reads this, the scripts are not compatible with python3(due to some arguments such as maketrans being deprecated in py3, 2.7 works fine). 

Thank you.
Sofina

**Comment by alexfields** [comment] 2017-07-01 04:58
Hi Sofina,
That error generally means there weren't any transcripts that passed the filters. One cause would be if your alignments are in transcriptome coordinates (alignments must be in genomic coordinates). An alternative reason might be if your sequencing depth is very low and none of the transcripts are meeting the minimum depth requirement. If you can rule out both of those possibilities and still have the problem, let me know and I'll see what I can do.
Best,
Alex

**Comment by sofinabegum** [comment] 2017-07-03 12:21
Hi Alex,
The alignments, I believe are already in genomic coordinates and the depth is ~60 million reads. What is the minimum depth requirement? 
Thank you,
Sofina

**Comment by alexfields** [comment] 2017-07-03 23:24
The minimum depth is set by the `--minreads` flag; default is 64 reads for a transcript to be included.

Usually this error indicates an incompatibility between the BAM file, BED file, and/or FASTA file. If you're confident that the BAM file is indeed aligned in genomic coordinates, then perhaps there is a chromosome name mismatch. Try running the following commands (replacing the placeholders with the appropriate filenames) to ensure that the chromosome names all match:
`samtools idxstats BAMFILE.BAM | cut -f 1`
`cut -f 1 < BEDFILE.BED | sort | uniq`
`grep "^>" FASTAFILE.FA`

If those all match, maybe you can paste the command line you're running for your alignments?

Best,
Alex

**Comment by sofinabegum** [comment] 2017-07-04 15:11
Hi Alex, 
Thanks for the quick reply! :)
There was actually an incompatibility between the BED file and the other two files. I removed the mismatches of the random chr, but I'm still getting the same error. 

The command line I've been using is: 

```
`python2.7 prune_transcripts.py --minreads 24 --inbed ~/Documents/Ribo_Seq_bed_transcripts/RP1_transcripts_2.bed --outbed RP1_prune.bed --summarytable RP1_removal_summary.txt -p 4 -v ~/Documents/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa ~/Documents/Riboseq_genome/RP1_vs_genome/accepted_hits.bam > logfile.out

Traceback (most recent call last):
  File "prune_transcripts.py", line 229, in <module>
    mm_df = workers.map(_find_mm_in_range, range(npart))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: No objects to concatenate
`
```
Thanks again,
Sofina

**Comment by alexfields** [comment] 2017-07-04 21:11
The command line looks fine to me. Is `RP1_transcripts_2.bed` formatted as a BED12 (i.e. 12 columns in each line)?
Can you verify that there are alignments in the BAM file that overlap (on the same strand) with your BED transcripts? (You could do a spot check in IGV, or run `bedtools coverage`)
Can you show me the command line you ran that generated your BAM file?

**Comment by sofinabegum** [comment] 2017-07-05 13:28
Hey Alex, 

The BED files are all in BED12 format. 
Checked the alignments via bedtools and they all overlap on the same strand.
The command line I used to generate my BAM file was: 

`tophat -p --bowtie1 --GTF Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf --no-novel-juncs --output-dir RP1_vs_genome/ Homo_sapiens/UCSC/hg19/Sequence/BowtieIndex/genome RP1_norrna.fq`

I then extracted the perfect read alignments from this output, using samtools. 

Thank you,
Sofina

**Comment by alexfields** [comment] 2017-07-05 17:30
The `tophat` command line looks OK too. I generally include the option `--max-multihits=64`, but the default value of 20 shouldn't be fatal.

Can you also show me the `samtools` line you are running to extract the perfect read alignments?

The script should be generating temporary files in a folder named `tid_seq_info_temp` (or `tid_seq_info_temp_1`, etc). Normally, those files would be deleted after the code completes, but in this case they should still be there since the program didn't exit normally. Can you tell me what files (if any) are present in that folder?

At this point, I'm starting to suspect that it will be easier for me to debug the issue if I have access to your inputs. If it's OK with you, would you be able to share with me your BED and BAM files? If you like, you could just include a single chromosome (e.g. `grep "^chr21" < RP1_transcripts_2.bed > chr21_transcripts.bed` and `samtools view -b accepted_hits.bam chr21 -o chr21_alignments.bam`). It appears you're using the regular UCSC hg19 `genome.fa`, which I can obtain myself.

**Comment by sofinabegum** [comment] 2017-07-05 18:43
I'm currently not at my desk, but it would be great if I could send you my files. Is there any other platform I could send you my files on?

**Comment by alexfields** [comment] 2017-07-05 22:13
Probably the simplest would be to upload your files to a folder on Box, Dropbox, or Google Drive, and then share that folder with me (email redacted).

**Comment by alexfields** [comment] 2017-07-06 22:17
I took a look at your files, and the problem is that there are very few reads (50886 according to samtools) in the accepted_hits.bam file, so no transcript has sufficient depth to be included. ORF-RATER definitely needs greater coverage than that to work. Actually, almost any tool will need greater coverage than that. There are three possible explanations for such low coverage: 1) low raw sequencing depth; 2) high fraction of unusable sequences (e.g. rRNA) in the library; or 3) some problem with the alignment process.

Anyway, this problem is not related to the ORF-RATER software itself, so I'm going to close the issue. Feel free to email me if you'd like to troubleshoot the low read coverage.

**Closed as completed by alexfields** 2017-07-06 22:17 UTC
